#!/bin/bash -e
spath=$( cd "$(dirname "$0")" ; pwd -P )
curdir=$( pwd -P )
source $spath/utils/android

usage() {
	echo "androdeb"
	echo "	shell		Enter the androdeb shell environment and get to work!"
	echo ""
	echo "	prepare		Prepare the device (when running for the first time)"
	echo "	--tracers	Enable tracing packages (perf and trace-cmd)"
	echo "	--compilers	Enable compilers on the FS (gcc and clang)"
	echo "	--editors	Enable vim, emacs and git packages"
	echo "	--scheduler	scheduler testing tools (only rt-app for now)"
	echo "	--bcc		Build and install BCC from source"
	echo "	--fullbuild	Enable all of the above tools"
	echo ""
	echo "	--kernelsrc	path-to-kernel-sources (can be used for bcc)"
	echo "	--tempdir	use a specific temporary directory"
	echo "	--distro	Debian distro to base on (default is buster)"
	exit 1
}

# Set default vars
DISTRO=buster;      PACKAGES="";	ARCH=arm64

# Parse command line parameters
if [ $# -lt 1 ]; then usage; fi; POSITIONAL=()
while [[ $# -gt 0 ]]; do key="$1";
case $key in
    prepare) PREP=1;     shift || true;    ;;
    shell) ASHELL=1;     shift || true;     ;;
    --tracers) source $spath/packages/tracers; shift || true; ;;
    --compilers) source $spath/packages/compilers; shift || true; ;;
    --editors) source $spath/packages/editors; shift || true; ;;
    --scheduler) source $spath/packages/scheduler; shift || true; ;;
    --fullbuild) for f in $(ls $spath/packages); do source packages/$f; done; shift || true; ;;
    --bcc) source $spath/packages/bcc; INSTALL_BCC=1; shift || true;     ;;
    --kernelsrc) KERNELSRC="$2"; shift || true;     shift || true;     ;;
    --tempdir) TDIR="$2"; shift || true;     shift || true;     ;;
    *) echo "Unknown option ($1)"; usage; ;;
esac
done

if [[ ! -z ${PREP+x} ]] && [[ "x$PACKAGES" == "x" ]]; then
	echo "Need to specifify something to prepare"; usage;
fi
PACKAGES+="\
bash
ca-certifcates
"

##########################################################
#  SHELL
##########################################################
if [[ ! -z ${ASHELL+x} ]]; then
	set +e; adb shell ls /data/androdeb/debian/.bashrc > /dev/null 2>&1
	if [ $? -ne 0 ]; then
	   die 2 "Device doesn't have an androdeb environment, run \"./androdeb prepare\" first";
	fi; set -e

	echo "For a better shell experience, run the following commands:"
	echo "    adb shell"
	echo "    /data/androdeb/run"
	adb shell -x /data/androdeb/run
	exit 0
fi

##########################################################
#  PREPARE 
##########################################################
if [[ $EUID -ne 0 ]]; then echo "For prepare, this tool must run as root";
echo "Try ./sudo androdeb prepare <other-args>"; exit 3; fi

# Where do we want to store temporary files
MKTEMP=0; if [[ -z ${TDIR+x} ]]  || [[ ! -d "${TDIR}" ]]; then
	TDIR=`mktemp -d`; MKTEMP=1; fi

OUT_TMP=$TDIR/debian; rm -rf $OUT_TMP; mkdir -p $OUT_TMP

echo "Full package list: $PACKAGES"
echo "Using temporary directory: $OUT_TMP"

time qemu-debootstrap --arch arm64 --include=$(make_csv "$PACKAGES") \
	$DISTRO $OUT_TMP http://deb.debian.org/debian/

# Some reason debootstrap leaves these founded
umount $OUT_TMP/proc/sys/fs/binfmt_misc
umount $OUT_TMP/proc

# Make bash the default shell
chroot $OUT_TMP rm /bin/sh || true
chroot $OUT_TMP ln -s /bin/bash /bin/sh || true
cp $spath/addons/bashrc $OUT_TMP/.bashrc

# For mounting android partitions
mkdir $OUT_TMP/system
mkdir $OUT_TMP/vendor

# Cleanup
rm -rf $OUT_TMP/lib/udev/*
rm -rf $OUT_TMP/var/lib/apt/lists/*
rm -rf $OUT_TMP/var/cache/apt/archives/*deb
rm -rf $OUT_TMP/usr/share/locale/*
rm -rf $OUT_TMP/usr/lib/share/locale/*
rm -rf $OUT_TMP/usr/share/doc/*
rm -rf $OUT_TMP/usr/lib/share/doc/*
rm -rf $OUT_TMP/usr/share/ieee-data/*
rm -rf $OUT_TMP/usr/lib/share/ieee-data/*
rm -rf $OUT_TMP/usr/share/man/*
rm -rf $OUT_TMP/usr/lib/share/man/*

# Clone BCC if needed
if [[ ! -z ${INSTALL_BCC+x} ]]; then
git clone https://github.com/iovisor/bcc.git $TDIR/debian/bcc-master
cp $spath/bcc/build-bcc.sh $TDIR/debian/bcc-master/
fi

echo "Compressing new filesystem to prepare to push to Android /data/androdeb/"
tar -zcf $TDIR/deb.tar.gz -C $TDIR debian

# Push tar to device and start unpack
adb shell mkdir -p /data/androdeb/
adb push $TDIR/deb.tar.gz /data/androdeb/
adb push $spath/addons/device-* /data/androdeb/
adb shell /data/androdeb/device-unpack

# rm -rf $OUT_TMP; if [ $MKTEMP -eq 1 ]; then rm -rf $TDIR; fi

# Use --foreign and --variant=minbase to build minimal deb first stage
# Use fakeroot tar to build tar with root files
