#!/bin/bash

spath="$(dirname "$(readlink -f "$0")")"
source $spath/utils/android
source $spath/utils/banners

ARCH=$1
DISTRO=$2
TDIR=$3
OUT_TMP=$4
PACKAGES=$5
INSTALL_BCC=$6
MIRROR=$7

root=sudo

if [ $EUID -ne 0 ]; then echo "The next stage runs as sudo, please enter password if asked."; fi

# It's easier to just really be root for debootstrap
time $root qemu-debootstrap --arch $ARCH --include="$(make_csv "$PACKAGES")" \
	$DISTRO $OUT_TMP $MIRROR

# Some reason debootstrap leaves these mounted
$root umount $OUT_TMP/proc/sys/fs/binfmt_misc || true
$root umount $OUT_TMP/proc || true

# Make bash the default shell
$root ln -sf /bin/bash $OUT_TMP/bin/sh || true
$root cp $spath/addons/bashrc $OUT_TMP/.bashrc

# Cleanup
$root rm -rf $OUT_TMP/lib/udev/*
$root rm -rf $OUT_TMP/var/lib/apt/lists/*
$root rm -rf $OUT_TMP/var/cache/apt/archives/*deb
$root rm -rf $OUT_TMP/usr/share/locale/*
$root rm -rf $OUT_TMP/usr/lib/share/locale/*
$root rm -rf $OUT_TMP/usr/share/doc/*
$root rm -rf $OUT_TMP/usr/lib/share/doc/*
$root rm -rf $OUT_TMP/usr/share/ieee-data/*
$root rm -rf $OUT_TMP/usr/lib/share/ieee-data/*
$root rm -rf $OUT_TMP/usr/share/man/*
$root rm -rf $OUT_TMP/usr/lib/share/man/*

# Clone BCC if needed
if [[ ! -z ${INSTALL_BCC:+x} ]]; then
git clone https://github.com/iovisor/bcc.git $TDIR/debian/bcc-master
cp $spath/bcc/build-bcc.sh $TDIR/debian/bcc-master/; fi

echo "Compressing new filesystem to prepare to push to Android /data/androdeb/"
$root tar -zpcf $TDIR/deb.tar.gz -C $TDIR debian

$root chown --reference=$TDIR $TDIR/deb.tar.gz
