#!/system/bin/sh
spath=$( cd "$(dirname "$0")" ; pwd -P )

cd $spath

# tear everything down
./device-umount-all

mount --bind /proc debian/proc/ > /dev/null
mount --bind /dev debian/dev/ > /dev/null
mount --bind /sys debian/sys/ > /dev/null
mount --bind /sys/kernel/debug/ debian/sys/kernel/debug/ > /dev/null
mount --bind /sys/kernel/debug/tracing/ debian/sys/kernel/debug/tracing/

# Mount Android partitions
if [ -d /d/ ]; then
	ln -s /sys/kernel/debug debian/d
fi

if [ -d /data/ ]; then
	mkdir -p debian/data/
	mount --bind /data debian/data/
fi

if [ -d /system/ ]; then
	mkdir -p debian/system/
	mount --bind /system debian/system/
fi

if [ -d /vendor/ ]; then
	mkdir -p debian/vendor/
	mount --bind /vendor debian/vendor/
fi

chroot debian/ /bin/bash

# tear everything down
./device-umount-all
