#!/system/bin/sh
spath=$( cd "$(dirname "$0")" ; pwd -P )
cd $spath

# Directly execute a command within the chroot of an Android device
CMD="$*"

chroot debian /bin/bash --rcfile '.bashrc.silent' -i -c "$CMD"
