#!/bin/bash -e
spath=$( cd "$(dirname "$0")" ; pwd -P )
curdir=$( pwd -P )

source $spath/utils/android

if [[ $EUID -ne 0 ]]; then echo "This tool must be run as root"; exit 3; fi

usage() {
	echo "androdeb"
	echo "	shell		Enter the androdeb shell environment and get to work!"
	echo ""
	echo "	prepare		Prepare the device (when running for the first time)"
	echo "	--tracers	Enable tracing packages (perf and trace-cmd)"
	echo "	--compilers	Enable compilers on the FS (gcc and clang)"
	echo "	--editors	Enable vim, emacs and git packages"
	echo "	--scheduler	scheduler testing tools (only rt-app for now)"
	echo "	--bcc		Build and install BCC from source"
	echo "	--fullbuild	Enable all of the above tools"
	echo ""
	echo "	--kernelsrc	path-to-kernel-sources (can be used for bcc)"
	echo "	--tempdir	use a specific temporary directory"
	echo "	--distro	Debian distro to base on (default is buster)"
	exit 1
}

# Set default vars
DISTRO=buster;      PACKAGES="bash";	ARCH=arm64

# Parse command line parameters
if [ $# -lt 1 ]; then usage; fi; POSITIONAL=()
while [[ $# -gt 0 ]]; do key="$1";
case $key in
    prepare) PREP=1;     shift || true;    ;;
    shell) SHELL=1;     shift || true;     ;;
    --tracers) source $spath/packages/tracers; shift || true; ;;
    --compilers) source $spath/packages/compilers; shift || true; ;;
    --editors) source $spath/packages/editors; shift || true; ;;
    --scheduler) source $spath/packages/scheduler; shift || true; ;;
    --fullbuild) for f in $(ls $spath/packages); do source packages/$f; done; shift || true; ;;
    --bcc) source $spath/packages/bcc; BCC=1; shift || true;     ;;
    --kernelsrc) KERNELSRC="$2"; shift || true;     shift || true;     ;;
    --tempdir) TMPDIR="$2"; shift || true;     shift || true;     ;;
    *) echo "Unknown option ($1)"; usage; ;;
esac
done

if [[ ! -z ${PREP+x} ]] && [[ "x$PACKAGES" == "x" ]]; then
	echo "Need to specifify something to prepare"; usage;
fi

##########################################################
#  PREPARE                                               #
##########################################################
# Where do we want to store temporary files
MKTEMP=0; if [[ -z ${TMPDIR+x} ]]  || [[ ! -d "${TMPDIR}" ]]; then
	TMPDIR=`mktemp -d`; MKTEMP=1; fi

OUT_TMP=$TMPDIR/debian; rm -rf $OUT_TMP; mkdir -p $OUT_TMP

echo "Full package list: $PACKAGES"
echo "Using temporary directory: $OUT_TMP"

time qemu-debootstrap --arch arm64 --include=$(make_csv "$PACKAGES") \
	--variant=minbase $DISTRO $OUT_TMP http://deb.debian.org/debian/

# Some reason debootstrap leaves these founded
umount $OUT_TMP/proc/sys/fs/binfmt_misc
umount $OUT_TMP/proc

# Make bash the default shell
chroot $OUT_TMP rm /bin/sh || true
chroot $OUT_TMP ln -s /bin/bash /bin/sh || true
cp $spath/addons/bashrc $OUT_TMP/.bashrc

# Cleanup
rm -rf $OUT_TMP/lib/udev/*
rm -rf $OUT_TMP/var/lib/apt/lists/*
rm -rf $OUT_TMP/var/cache/apt/archives/*deb
rm -rf $OUT_TMP/usr/share/locale/*
rm -rf $OUT_TMP/usr/lib/share/locale/*
rm -rf $OUT_TMP/usr/share/doc/*
rm -rf $OUT_TMP/usr/lib/share/doc/*
rm -rf $OUT_TMP/usr/share/ieee-data/*
rm -rf $OUT_TMP/usr/lib/share/ieee-data/*
rm -rf $OUT_TMP/usr/share/man/*
rm -rf $OUT_TMP/usr/lib/share/man/*

echo "Compressing new filesystem to prepare to push to Android /data/androdeb/"
tar -zcf $OUT_TMP/deb.tar.gz -C $OUT_TMP debian

# rm -rf $OUT_TMP; if [ $MKTEMP -eq 1 ]; then rm -rf $TMPDIR; fi

# Use --foreign and --variant=minbase to build minimal deb first stage
# Use fakeroot tar to build tar with root files
